# Generated by Django 4.2.5 on 2023-09-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acaunts_for_get',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acaunts_href', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acaunts_for_get',
            },
        ),
        migrations.CreateModel(
            name='Instagram_acaunts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField()),
                ('password', models.TextField()),
                ('instagram_acaunts_for_get', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Potoci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promt', models.TextField(null=True)),
                ('chice_answer', models.TextField(choices=[('text', 'text'), ('text_with_gpt', 'text_with_gpt')])),
                ('acaunts', models.ManyToManyField(to='app1.instagram_acaunts')),
            ],
        ),
    ]
