# Generated by Django 4.2.5 on 2023-10-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_acaunts_for_get_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaunts_for_get',
            name='send_massage_point',
            field=models.TextField(choices=[('send_massage', 'send_massage'), ('not_send_massage', 'not_send_massage')], default='not_send_massage'),
        ),
        migrations.AlterField(
            model_name='acaunts_for_get',
            name='acaunts_href',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
