# Generated by Django 4.2.5 on 2023-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_acaunts_for_get_send_massage_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_acaunts',
            name='enter_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
